	Nios_CPU_qsys u0 (
		.clk_clk                                                    (<connected-to-clk_clk>),                                                    //                                 clk.clk
		.merged_resets_in_reset_reset_n                             (<connected-to-merged_resets_in_reset_reset_n>),                             //              merged_resets_in_reset.reset_n
		.tse_mac_mac_gmii_connection_gmii_rx_d                      (<connected-to-tse_mac_mac_gmii_connection_gmii_rx_d>),                      //         tse_mac_mac_gmii_connection.gmii_rx_d
		.tse_mac_mac_gmii_connection_gmii_rx_dv                     (<connected-to-tse_mac_mac_gmii_connection_gmii_rx_dv>),                     //                                    .gmii_rx_dv
		.tse_mac_mac_gmii_connection_gmii_rx_err                    (<connected-to-tse_mac_mac_gmii_connection_gmii_rx_err>),                    //                                    .gmii_rx_err
		.tse_mac_mac_gmii_connection_gmii_tx_d                      (<connected-to-tse_mac_mac_gmii_connection_gmii_tx_d>),                      //                                    .gmii_tx_d
		.tse_mac_mac_gmii_connection_gmii_tx_en                     (<connected-to-tse_mac_mac_gmii_connection_gmii_tx_en>),                     //                                    .gmii_tx_en
		.tse_mac_mac_gmii_connection_gmii_tx_err                    (<connected-to-tse_mac_mac_gmii_connection_gmii_tx_err>),                    //                                    .gmii_tx_err
		.tse_mac_mac_mdio_connection_mdc                            (<connected-to-tse_mac_mac_mdio_connection_mdc>),                            //         tse_mac_mac_mdio_connection.mdc
		.tse_mac_mac_mdio_connection_mdio_in                        (<connected-to-tse_mac_mac_mdio_connection_mdio_in>),                        //                                    .mdio_in
		.tse_mac_mac_mdio_connection_mdio_out                       (<connected-to-tse_mac_mac_mdio_connection_mdio_out>),                       //                                    .mdio_out
		.tse_mac_mac_mdio_connection_mdio_oen                       (<connected-to-tse_mac_mac_mdio_connection_mdio_oen>),                       //                                    .mdio_oen
		.tse_mac_mac_mii_connection_mii_rx_d                        (<connected-to-tse_mac_mac_mii_connection_mii_rx_d>),                        //          tse_mac_mac_mii_connection.mii_rx_d
		.tse_mac_mac_mii_connection_mii_rx_dv                       (<connected-to-tse_mac_mac_mii_connection_mii_rx_dv>),                       //                                    .mii_rx_dv
		.tse_mac_mac_mii_connection_mii_rx_err                      (<connected-to-tse_mac_mac_mii_connection_mii_rx_err>),                      //                                    .mii_rx_err
		.tse_mac_mac_mii_connection_mii_tx_d                        (<connected-to-tse_mac_mac_mii_connection_mii_tx_d>),                        //                                    .mii_tx_d
		.tse_mac_mac_mii_connection_mii_tx_en                       (<connected-to-tse_mac_mac_mii_connection_mii_tx_en>),                       //                                    .mii_tx_en
		.tse_mac_mac_mii_connection_mii_tx_err                      (<connected-to-tse_mac_mac_mii_connection_mii_tx_err>),                      //                                    .mii_tx_err
		.tse_mac_mac_mii_connection_mii_crs                         (<connected-to-tse_mac_mac_mii_connection_mii_crs>),                         //                                    .mii_crs
		.tse_mac_mac_mii_connection_mii_col                         (<connected-to-tse_mac_mac_mii_connection_mii_col>),                         //                                    .mii_col
		.tse_mac_mac_misc_connection_xon_gen                        (<connected-to-tse_mac_mac_misc_connection_xon_gen>),                        //         tse_mac_mac_misc_connection.xon_gen
		.tse_mac_mac_misc_connection_xoff_gen                       (<connected-to-tse_mac_mac_misc_connection_xoff_gen>),                       //                                    .xoff_gen
		.tse_mac_mac_misc_connection_ff_tx_crc_fwd                  (<connected-to-tse_mac_mac_misc_connection_ff_tx_crc_fwd>),                  //                                    .ff_tx_crc_fwd
		.tse_mac_mac_misc_connection_ff_tx_septy                    (<connected-to-tse_mac_mac_misc_connection_ff_tx_septy>),                    //                                    .ff_tx_septy
		.tse_mac_mac_misc_connection_tx_ff_uflow                    (<connected-to-tse_mac_mac_misc_connection_tx_ff_uflow>),                    //                                    .tx_ff_uflow
		.tse_mac_mac_misc_connection_ff_tx_a_full                   (<connected-to-tse_mac_mac_misc_connection_ff_tx_a_full>),                   //                                    .ff_tx_a_full
		.tse_mac_mac_misc_connection_ff_tx_a_empty                  (<connected-to-tse_mac_mac_misc_connection_ff_tx_a_empty>),                  //                                    .ff_tx_a_empty
		.tse_mac_mac_misc_connection_rx_err_stat                    (<connected-to-tse_mac_mac_misc_connection_rx_err_stat>),                    //                                    .rx_err_stat
		.tse_mac_mac_misc_connection_rx_frm_type                    (<connected-to-tse_mac_mac_misc_connection_rx_frm_type>),                    //                                    .rx_frm_type
		.tse_mac_mac_misc_connection_ff_rx_dsav                     (<connected-to-tse_mac_mac_misc_connection_ff_rx_dsav>),                     //                                    .ff_rx_dsav
		.tse_mac_mac_misc_connection_ff_rx_a_full                   (<connected-to-tse_mac_mac_misc_connection_ff_rx_a_full>),                   //                                    .ff_rx_a_full
		.tse_mac_mac_misc_connection_ff_rx_a_empty                  (<connected-to-tse_mac_mac_misc_connection_ff_rx_a_empty>),                  //                                    .ff_rx_a_empty
		.tse_mac_mac_status_connection_set_10                       (<connected-to-tse_mac_mac_status_connection_set_10>),                       //       tse_mac_mac_status_connection.set_10
		.tse_mac_mac_status_connection_set_1000                     (<connected-to-tse_mac_mac_status_connection_set_1000>),                     //                                    .set_1000
		.tse_mac_mac_status_connection_eth_mode                     (<connected-to-tse_mac_mac_status_connection_eth_mode>),                     //                                    .eth_mode
		.tse_mac_mac_status_connection_ena_10                       (<connected-to-tse_mac_mac_status_connection_ena_10>),                       //                                    .ena_10
		.tse_mac_pcs_mac_rx_clock_connection_clk                    (<connected-to-tse_mac_pcs_mac_rx_clock_connection_clk>),                    // tse_mac_pcs_mac_rx_clock_connection.clk
		.tse_mac_pcs_mac_tx_clock_connection_clk                    (<connected-to-tse_mac_pcs_mac_tx_clock_connection_clk>),                    // tse_mac_pcs_mac_tx_clock_connection.clk
		.oct_rzqin                                                  (<connected-to-oct_rzqin>),                                                  //                                 oct.rzqin
		.memory_mem_ca                                              (<connected-to-memory_mem_ca>),                                              //                              memory.mem_ca
		.memory_mem_ck                                              (<connected-to-memory_mem_ck>),                                              //                                    .mem_ck
		.memory_mem_ck_n                                            (<connected-to-memory_mem_ck_n>),                                            //                                    .mem_ck_n
		.memory_mem_cke                                             (<connected-to-memory_mem_cke>),                                             //                                    .mem_cke
		.memory_mem_cs_n                                            (<connected-to-memory_mem_cs_n>),                                            //                                    .mem_cs_n
		.memory_mem_dm                                              (<connected-to-memory_mem_dm>),                                              //                                    .mem_dm
		.memory_mem_dq                                              (<connected-to-memory_mem_dq>),                                              //                                    .mem_dq
		.memory_mem_dqs                                             (<connected-to-memory_mem_dqs>),                                             //                                    .mem_dqs
		.memory_mem_dqs_n                                           (<connected-to-memory_mem_dqs_n>),                                           //                                    .mem_dqs_n
		.mem_if_lpddr2_emif_0_pll_sharing_pll_mem_clk               (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_mem_clk>),               //    mem_if_lpddr2_emif_0_pll_sharing.pll_mem_clk
		.mem_if_lpddr2_emif_0_pll_sharing_pll_write_clk             (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_write_clk>),             //                                    .pll_write_clk
		.mem_if_lpddr2_emif_0_pll_sharing_pll_locked                (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_locked>),                //                                    .pll_locked
		.mem_if_lpddr2_emif_0_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_write_clk_pre_phy_clk>), //                                    .pll_write_clk_pre_phy_clk
		.mem_if_lpddr2_emif_0_pll_sharing_pll_addr_cmd_clk          (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_addr_cmd_clk>),          //                                    .pll_addr_cmd_clk
		.mem_if_lpddr2_emif_0_pll_sharing_pll_avl_clk               (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_avl_clk>),               //                                    .pll_avl_clk
		.mem_if_lpddr2_emif_0_pll_sharing_pll_config_clk            (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_config_clk>),            //                                    .pll_config_clk
		.mem_if_lpddr2_emif_0_pll_sharing_pll_mem_phy_clk           (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_mem_phy_clk>),           //                                    .pll_mem_phy_clk
		.mem_if_lpddr2_emif_0_pll_sharing_afi_phy_clk               (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_afi_phy_clk>),               //                                    .afi_phy_clk
		.mem_if_lpddr2_emif_0_pll_sharing_pll_avl_phy_clk           (<connected-to-mem_if_lpddr2_emif_0_pll_sharing_pll_avl_phy_clk>),           //                                    .pll_avl_phy_clk
		.mem_if_lpddr2_emif_0_status_local_init_done                (<connected-to-mem_if_lpddr2_emif_0_status_local_init_done>),                //         mem_if_lpddr2_emif_0_status.local_init_done
		.mem_if_lpddr2_emif_0_status_local_cal_success              (<connected-to-mem_if_lpddr2_emif_0_status_local_cal_success>),              //                                    .local_cal_success
		.mem_if_lpddr2_emif_0_status_local_cal_fail                 (<connected-to-mem_if_lpddr2_emif_0_status_local_cal_fail>)                  //                                    .local_cal_fail
	);

