	eth_std_main_system u0 (
		.clk_50_clk_in_clk                           (<connected-to-clk_50_clk_in_clk>),                           //                  clk_50_clk_in.clk
		.clk_50_clk_in_reset_reset_n                 (<connected-to-clk_50_clk_in_reset_reset_n>),                 //            clk_50_clk_in_reset.reset_n
		.ddr2_top_memory_mem_ca                      (<connected-to-ddr2_top_memory_mem_ca>),                      //                ddr2_top_memory.mem_ca
		.ddr2_top_memory_mem_ck                      (<connected-to-ddr2_top_memory_mem_ck>),                      //                               .mem_ck
		.ddr2_top_memory_mem_ck_n                    (<connected-to-ddr2_top_memory_mem_ck_n>),                    //                               .mem_ck_n
		.ddr2_top_memory_mem_cke                     (<connected-to-ddr2_top_memory_mem_cke>),                     //                               .mem_cke
		.ddr2_top_memory_mem_cs_n                    (<connected-to-ddr2_top_memory_mem_cs_n>),                    //                               .mem_cs_n
		.ddr2_top_memory_mem_dm                      (<connected-to-ddr2_top_memory_mem_dm>),                      //                               .mem_dm
		.ddr2_top_memory_mem_dq                      (<connected-to-ddr2_top_memory_mem_dq>),                      //                               .mem_dq
		.ddr2_top_memory_mem_dqs                     (<connected-to-ddr2_top_memory_mem_dqs>),                     //                               .mem_dqs
		.ddr2_top_memory_mem_dqs_n                   (<connected-to-ddr2_top_memory_mem_dqs_n>),                   //                               .mem_dqs_n
		.enet_pll_reset_reset                        (<connected-to-enet_pll_reset_reset>),                        //                 enet_pll_reset.reset
		.enet_pll_clk125_clk                         (<connected-to-enet_pll_clk125_clk>),                         //                enet_pll_clk125.clk
		.enet_pll_clk25_clk                          (<connected-to-enet_pll_clk25_clk>),                          //                 enet_pll_clk25.clk
		.enet_pll_locked_export                      (<connected-to-enet_pll_locked_export>),                      //                enet_pll_locked.export
		.enet_pll_clk2_5_clk                         (<connected-to-enet_pll_clk2_5_clk>),                         //                enet_pll_clk2_5.clk
		.button_pio_external_connection_export       (<connected-to-button_pio_external_connection_export>),       // button_pio_external_connection.export
		.led_pio_external_connection_export          (<connected-to-led_pio_external_connection_export>),          //    led_pio_external_connection.export
		.emac_gmii_connection_gmii_rx_d              (<connected-to-emac_gmii_connection_gmii_rx_d>),              //           emac_gmii_connection.gmii_rx_d
		.emac_gmii_connection_gmii_rx_dv             (<connected-to-emac_gmii_connection_gmii_rx_dv>),             //                               .gmii_rx_dv
		.emac_gmii_connection_gmii_rx_err            (<connected-to-emac_gmii_connection_gmii_rx_err>),            //                               .gmii_rx_err
		.emac_gmii_connection_gmii_tx_d              (<connected-to-emac_gmii_connection_gmii_tx_d>),              //                               .gmii_tx_d
		.emac_gmii_connection_gmii_tx_en             (<connected-to-emac_gmii_connection_gmii_tx_en>),             //                               .gmii_tx_en
		.emac_gmii_connection_gmii_tx_err            (<connected-to-emac_gmii_connection_gmii_tx_err>),            //                               .gmii_tx_err
		.emac_mdio_connection_mdc                    (<connected-to-emac_mdio_connection_mdc>),                    //           emac_mdio_connection.mdc
		.emac_mdio_connection_mdio_in                (<connected-to-emac_mdio_connection_mdio_in>),                //                               .mdio_in
		.emac_mdio_connection_mdio_out               (<connected-to-emac_mdio_connection_mdio_out>),               //                               .mdio_out
		.emac_mdio_connection_mdio_oen               (<connected-to-emac_mdio_connection_mdio_oen>),               //                               .mdio_oen
		.emac_mii_connection_mii_rx_d                (<connected-to-emac_mii_connection_mii_rx_d>),                //            emac_mii_connection.mii_rx_d
		.emac_mii_connection_mii_rx_dv               (<connected-to-emac_mii_connection_mii_rx_dv>),               //                               .mii_rx_dv
		.emac_mii_connection_mii_rx_err              (<connected-to-emac_mii_connection_mii_rx_err>),              //                               .mii_rx_err
		.emac_mii_connection_mii_tx_d                (<connected-to-emac_mii_connection_mii_tx_d>),                //                               .mii_tx_d
		.emac_mii_connection_mii_tx_en               (<connected-to-emac_mii_connection_mii_tx_en>),               //                               .mii_tx_en
		.emac_mii_connection_mii_tx_err              (<connected-to-emac_mii_connection_mii_tx_err>),              //                               .mii_tx_err
		.emac_mii_connection_mii_crs                 (<connected-to-emac_mii_connection_mii_crs>),                 //                               .mii_crs
		.emac_mii_connection_mii_col                 (<connected-to-emac_mii_connection_mii_col>),                 //                               .mii_col
		.emac_status_connection_set_10               (<connected-to-emac_status_connection_set_10>),               //         emac_status_connection.set_10
		.emac_status_connection_set_1000             (<connected-to-emac_status_connection_set_1000>),             //                               .set_1000
		.emac_status_connection_eth_mode             (<connected-to-emac_status_connection_eth_mode>),             //                               .eth_mode
		.emac_status_connection_ena_10               (<connected-to-emac_status_connection_ena_10>),               //                               .ena_10
		.emac_misc_connection_xon_gen                (<connected-to-emac_misc_connection_xon_gen>),                //           emac_misc_connection.xon_gen
		.emac_misc_connection_xoff_gen               (<connected-to-emac_misc_connection_xoff_gen>),               //                               .xoff_gen
		.emac_misc_connection_ff_tx_crc_fwd          (<connected-to-emac_misc_connection_ff_tx_crc_fwd>),          //                               .ff_tx_crc_fwd
		.emac_misc_connection_ff_tx_septy            (<connected-to-emac_misc_connection_ff_tx_septy>),            //                               .ff_tx_septy
		.emac_misc_connection_tx_ff_uflow            (<connected-to-emac_misc_connection_tx_ff_uflow>),            //                               .tx_ff_uflow
		.emac_misc_connection_ff_tx_a_full           (<connected-to-emac_misc_connection_ff_tx_a_full>),           //                               .ff_tx_a_full
		.emac_misc_connection_ff_tx_a_empty          (<connected-to-emac_misc_connection_ff_tx_a_empty>),          //                               .ff_tx_a_empty
		.emac_misc_connection_rx_err_stat            (<connected-to-emac_misc_connection_rx_err_stat>),            //                               .rx_err_stat
		.emac_misc_connection_rx_frm_type            (<connected-to-emac_misc_connection_rx_frm_type>),            //                               .rx_frm_type
		.emac_misc_connection_ff_rx_dsav             (<connected-to-emac_misc_connection_ff_rx_dsav>),             //                               .ff_rx_dsav
		.emac_misc_connection_ff_rx_a_full           (<connected-to-emac_misc_connection_ff_rx_a_full>),           //                               .ff_rx_a_full
		.emac_misc_connection_ff_rx_a_empty          (<connected-to-emac_misc_connection_ff_rx_a_empty>),          //                               .ff_rx_a_empty
		.emac_rx_clock_clk                           (<connected-to-emac_rx_clock_clk>),                           //                  emac_rx_clock.clk
		.emac_tx_clock_clk                           (<connected-to-emac_tx_clock_clk>),                           //                  emac_tx_clock.clk
		.clk_125_clk_in_clk                          (<connected-to-clk_125_clk_in_clk>),                          //                 clk_125_clk_in.clk
		.clk_125_clk_in_reset_reset_n                (<connected-to-clk_125_clk_in_reset_reset_n>),                //           clk_125_clk_in_reset.reset_n
		.ddr2_top_oct_rzqin                          (<connected-to-ddr2_top_oct_rzqin>),                          //                   ddr2_top_oct.rzqin
		.ddr2_top_status_local_init_done             (<connected-to-ddr2_top_status_local_init_done>),             //                ddr2_top_status.local_init_done
		.ddr2_top_status_local_cal_success           (<connected-to-ddr2_top_status_local_cal_success>),           //                               .local_cal_success
		.ddr2_top_status_local_cal_fail              (<connected-to-ddr2_top_status_local_cal_fail>),              //                               .local_cal_fail
		.sdram_pll_sharing_pll_mem_clk               (<connected-to-sdram_pll_sharing_pll_mem_clk>),               //              sdram_pll_sharing.pll_mem_clk
		.sdram_pll_sharing_pll_write_clk             (<connected-to-sdram_pll_sharing_pll_write_clk>),             //                               .pll_write_clk
		.sdram_pll_sharing_pll_locked                (<connected-to-sdram_pll_sharing_pll_locked>),                //                               .pll_locked
		.sdram_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-sdram_pll_sharing_pll_write_clk_pre_phy_clk>), //                               .pll_write_clk_pre_phy_clk
		.sdram_pll_sharing_pll_addr_cmd_clk          (<connected-to-sdram_pll_sharing_pll_addr_cmd_clk>),          //                               .pll_addr_cmd_clk
		.sdram_pll_sharing_pll_avl_clk               (<connected-to-sdram_pll_sharing_pll_avl_clk>),               //                               .pll_avl_clk
		.sdram_pll_sharing_pll_config_clk            (<connected-to-sdram_pll_sharing_pll_config_clk>),            //                               .pll_config_clk
		.sdram_pll_sharing_pll_mem_phy_clk           (<connected-to-sdram_pll_sharing_pll_mem_phy_clk>),           //                               .pll_mem_phy_clk
		.sdram_pll_sharing_afi_phy_clk               (<connected-to-sdram_pll_sharing_afi_phy_clk>),               //                               .afi_phy_clk
		.sdram_pll_sharing_pll_avl_phy_clk           (<connected-to-sdram_pll_sharing_pll_avl_phy_clk>)            //                               .pll_avl_phy_clk
	);

