	ethernet_system u0 (
		.ethernet_subsys_clk_in_clk       (<connected-to-ethernet_subsys_clk_in_clk>),       //   ethernet_subsys_clk_in.clk
		.ethernet_subsys_reset_in_reset_n (<connected-to-ethernet_subsys_reset_in_reset_n>), // ethernet_subsys_reset_in.reset_n
		.ethernet_bridge_s0_waitrequest   (<connected-to-ethernet_bridge_s0_waitrequest>),   //       ethernet_bridge_s0.waitrequest
		.ethernet_bridge_s0_readdata      (<connected-to-ethernet_bridge_s0_readdata>),      //                         .readdata
		.ethernet_bridge_s0_readdatavalid (<connected-to-ethernet_bridge_s0_readdatavalid>), //                         .readdatavalid
		.ethernet_bridge_s0_burstcount    (<connected-to-ethernet_bridge_s0_burstcount>),    //                         .burstcount
		.ethernet_bridge_s0_writedata     (<connected-to-ethernet_bridge_s0_writedata>),     //                         .writedata
		.ethernet_bridge_s0_address       (<connected-to-ethernet_bridge_s0_address>),       //                         .address
		.ethernet_bridge_s0_write         (<connected-to-ethernet_bridge_s0_write>),         //                         .write
		.ethernet_bridge_s0_read          (<connected-to-ethernet_bridge_s0_read>),          //                         .read
		.ethernet_bridge_s0_byteenable    (<connected-to-ethernet_bridge_s0_byteenable>),    //                         .byteenable
		.ethernet_bridge_s0_debugaccess   (<connected-to-ethernet_bridge_s0_debugaccess>),   //                         .debugaccess
		.sgdma_bridge_m0_waitrequest      (<connected-to-sgdma_bridge_m0_waitrequest>),      //          sgdma_bridge_m0.waitrequest
		.sgdma_bridge_m0_readdata         (<connected-to-sgdma_bridge_m0_readdata>),         //                         .readdata
		.sgdma_bridge_m0_readdatavalid    (<connected-to-sgdma_bridge_m0_readdatavalid>),    //                         .readdatavalid
		.sgdma_bridge_m0_burstcount       (<connected-to-sgdma_bridge_m0_burstcount>),       //                         .burstcount
		.sgdma_bridge_m0_writedata        (<connected-to-sgdma_bridge_m0_writedata>),        //                         .writedata
		.sgdma_bridge_m0_address          (<connected-to-sgdma_bridge_m0_address>),          //                         .address
		.sgdma_bridge_m0_write            (<connected-to-sgdma_bridge_m0_write>),            //                         .write
		.sgdma_bridge_m0_read             (<connected-to-sgdma_bridge_m0_read>),             //                         .read
		.sgdma_bridge_m0_byteenable       (<connected-to-sgdma_bridge_m0_byteenable>),       //                         .byteenable
		.sgdma_bridge_m0_debugaccess      (<connected-to-sgdma_bridge_m0_debugaccess>),      //                         .debugaccess
		.rx_clock_clk                     (<connected-to-rx_clock_clk>),                     //                 rx_clock.clk
		.tx_clock_clk                     (<connected-to-tx_clock_clk>),                     //                 tx_clock.clk
		.mac_status_connection_set_10     (<connected-to-mac_status_connection_set_10>),     //    mac_status_connection.set_10
		.mac_status_connection_set_1000   (<connected-to-mac_status_connection_set_1000>),   //                         .set_1000
		.mac_status_connection_eth_mode   (<connected-to-mac_status_connection_eth_mode>),   //                         .eth_mode
		.mac_status_connection_ena_10     (<connected-to-mac_status_connection_ena_10>),     //                         .ena_10
		.mac_gmii_connection_gmii_rx_d    (<connected-to-mac_gmii_connection_gmii_rx_d>),    //      mac_gmii_connection.gmii_rx_d
		.mac_gmii_connection_gmii_rx_dv   (<connected-to-mac_gmii_connection_gmii_rx_dv>),   //                         .gmii_rx_dv
		.mac_gmii_connection_gmii_rx_err  (<connected-to-mac_gmii_connection_gmii_rx_err>),  //                         .gmii_rx_err
		.mac_gmii_connection_gmii_tx_d    (<connected-to-mac_gmii_connection_gmii_tx_d>),    //                         .gmii_tx_d
		.mac_gmii_connection_gmii_tx_en   (<connected-to-mac_gmii_connection_gmii_tx_en>),   //                         .gmii_tx_en
		.mac_gmii_connection_gmii_tx_err  (<connected-to-mac_gmii_connection_gmii_tx_err>),  //                         .gmii_tx_err
		.mac_mdio_connection_mdc          (<connected-to-mac_mdio_connection_mdc>),          //      mac_mdio_connection.mdc
		.mac_mdio_connection_mdio_in      (<connected-to-mac_mdio_connection_mdio_in>),      //                         .mdio_in
		.mac_mdio_connection_mdio_out     (<connected-to-mac_mdio_connection_mdio_out>),     //                         .mdio_out
		.mac_mdio_connection_mdio_oen     (<connected-to-mac_mdio_connection_mdio_oen>),     //                         .mdio_oen
		.misc_connection_xon_gen          (<connected-to-misc_connection_xon_gen>),          //          misc_connection.xon_gen
		.misc_connection_xoff_gen         (<connected-to-misc_connection_xoff_gen>),         //                         .xoff_gen
		.misc_connection_ff_tx_crc_fwd    (<connected-to-misc_connection_ff_tx_crc_fwd>),    //                         .ff_tx_crc_fwd
		.misc_connection_ff_tx_septy      (<connected-to-misc_connection_ff_tx_septy>),      //                         .ff_tx_septy
		.misc_connection_tx_ff_uflow      (<connected-to-misc_connection_tx_ff_uflow>),      //                         .tx_ff_uflow
		.misc_connection_ff_tx_a_full     (<connected-to-misc_connection_ff_tx_a_full>),     //                         .ff_tx_a_full
		.misc_connection_ff_tx_a_empty    (<connected-to-misc_connection_ff_tx_a_empty>),    //                         .ff_tx_a_empty
		.misc_connection_rx_err_stat      (<connected-to-misc_connection_rx_err_stat>),      //                         .rx_err_stat
		.misc_connection_rx_frm_type      (<connected-to-misc_connection_rx_frm_type>),      //                         .rx_frm_type
		.misc_connection_ff_rx_dsav       (<connected-to-misc_connection_ff_rx_dsav>),       //                         .ff_rx_dsav
		.misc_connection_ff_rx_a_full     (<connected-to-misc_connection_ff_rx_a_full>),     //                         .ff_rx_a_full
		.misc_connection_ff_rx_a_empty    (<connected-to-misc_connection_ff_rx_a_empty>),    //                         .ff_rx_a_empty
		.mac_mii_connection_mii_rx_d      (<connected-to-mac_mii_connection_mii_rx_d>),      //       mac_mii_connection.mii_rx_d
		.mac_mii_connection_mii_rx_dv     (<connected-to-mac_mii_connection_mii_rx_dv>),     //                         .mii_rx_dv
		.mac_mii_connection_mii_rx_err    (<connected-to-mac_mii_connection_mii_rx_err>),    //                         .mii_rx_err
		.mac_mii_connection_mii_tx_d      (<connected-to-mac_mii_connection_mii_tx_d>),      //                         .mii_tx_d
		.mac_mii_connection_mii_tx_en     (<connected-to-mac_mii_connection_mii_tx_en>),     //                         .mii_tx_en
		.mac_mii_connection_mii_tx_err    (<connected-to-mac_mii_connection_mii_tx_err>),    //                         .mii_tx_err
		.mac_mii_connection_mii_crs       (<connected-to-mac_mii_connection_mii_crs>),       //                         .mii_crs
		.mac_mii_connection_mii_col       (<connected-to-mac_mii_connection_mii_col>),       //                         .mii_col
		.sgdma_tx_csr_irq_irq             (<connected-to-sgdma_tx_csr_irq_irq>),             //         sgdma_tx_csr_irq.irq
		.sgdma_rx_csr_irq_irq             (<connected-to-sgdma_rx_csr_irq_irq>),             //         sgdma_rx_csr_irq.irq
		.descriptor_memory_s2_address     (<connected-to-descriptor_memory_s2_address>),     //     descriptor_memory_s2.address
		.descriptor_memory_s2_chipselect  (<connected-to-descriptor_memory_s2_chipselect>),  //                         .chipselect
		.descriptor_memory_s2_clken       (<connected-to-descriptor_memory_s2_clken>),       //                         .clken
		.descriptor_memory_s2_write       (<connected-to-descriptor_memory_s2_write>),       //                         .write
		.descriptor_memory_s2_readdata    (<connected-to-descriptor_memory_s2_readdata>),    //                         .readdata
		.descriptor_memory_s2_writedata   (<connected-to-descriptor_memory_s2_writedata>),   //                         .writedata
		.descriptor_memory_s2_byteenable  (<connected-to-descriptor_memory_s2_byteenable>)   //                         .byteenable
	);

